FROM node:20.3.1-alpine

RUN apk --no-cache add curl

WORKDIR /opt/app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev


COPY prisma ./prisma
RUN npx prisma generate

COPY . .

RUN echo $(date +%s) > .cachebuster

RUN npm run build

EXPOSE 3330

CMD ["npm", "run", "start"]