name: api-brain-ci-release

on:
  push:
    tags:
      - v1.**

env:
  WEB_CONTAINER_PRODUCTION_IMAGE: ${{ vars.CI_REGISTRY_IMAGE_WEB }}:latest
  WEB_CONTAINER_PRODUCTION_TAG_IMAGE: ${{ vars.CI_REGISTRY_IMAGE_WEB }}:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Check version npm and install the dependencies
        run: |
          npm -v
          npm i
      - name: Lint and build application
        run: |
          npm run lint
          npm run build

  alpha:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_DEPLOY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build web image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile.web.prod
          push: true
          context: .
          tags: |
            ${{ env.WEB_CONTAINER_PRODUCTION_IMAGE }}
            ${{ env.WEB_CONTAINER_PRODUCTION_TAG_IMAGE }}
